### PR TITLE
Make sure the users table exists before trying to use it, eh?

### PR DESCRIPTION
**Pull request by robbkidd**

### CODE REVIEW

**Comment by llimllib** [comment]
We already have https://github.com/markolson/linkbot/blob/master/plugins/links.rb#L17 . Which is right?

**Comment by robbkidd** [comment]
Problem is there is an attempt to use the `users` table during the initialization of the `Linkbot::Db` class.

```
I know now why you cry. But it's something I can never do. 💀
/usr/local/bundle/gems/sqlite3-1.3.9/lib/sqlite3/database.rb:91:in `initialize': no such table: users (SQLite3::SQLException)
	from /usr/local/bundle/gems/sqlite3-1.3.9/lib/sqlite3/database.rb:91:in `new'
	from /usr/local/bundle/gems/sqlite3-1.3.9/lib/sqlite3/database.rb:91:in `prepare'
	from /usr/local/bundle/gems/sqlite3-1.3.9/lib/sqlite3/database.rb:134:in `execute'
	from /srv/linkbot/lib/linkbot/db.rb:12:in `load_users'
	from /srv/linkbot/lib/linkbot.rb:25:in `initialize'
	from bin/linkbot:42:in `new'
	from bin/linkbot:42:in `<main>'

**Comment by llimllib** [comment]
OK, then this should delete the CREATE TABLE from links.rb. Should all the create tables from that class go here?

**Comment by robbkidd** [comment]
Hmm. I don't think so. Given the methods in the `Db` class, it seems to be responsible for managing users as well as access to the database. The other tables created in the `links` plugin are links-specific which was a pattern I saw with other plugins.

I put those `CREATE TABLE` commands in the initialize method of the plugins when I moved them to instances so that if a plugin is able to be disabled, tables don't get created.

**Comment by robbkidd** [comment]
But I agree on removing the `CREATE TABLE users` out of the links plugin.

**Comment by llimllib** [comment]
yes I think it had worked previously because table creation was done at module load time, not at plugin initialization time.

**Comment by robbkidd** [comment]
:shipit: ?

**Pull request merged**
